// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManager.Data;

#nullable disable

namespace OrderManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("OrderManager.Models.OrderViewModel", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Freight")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            Freight = 10m,
                            OrderDate = new DateTime(2022, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample1",
                            ShipName = "ShipNameExample1"
                        },
                        new
                        {
                            OrderID = 2,
                            Freight = 20m,
                            OrderDate = new DateTime(2022, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample2",
                            ShipName = "ShipNameExample2"
                        },
                        new
                        {
                            OrderID = 3,
                            Freight = 30m,
                            OrderDate = new DateTime(2022, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample3",
                            ShipName = "ShipNameExample3"
                        },
                        new
                        {
                            OrderID = 4,
                            Freight = 40m,
                            OrderDate = new DateTime(2022, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample4",
                            ShipName = "ShipNameExample4"
                        },
                        new
                        {
                            OrderID = 5,
                            Freight = 50m,
                            OrderDate = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample5",
                            ShipName = "ShipNameExample5"
                        },
                        new
                        {
                            OrderID = 6,
                            Freight = 60m,
                            OrderDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample6",
                            ShipName = "ShipNameExample6"
                        },
                        new
                        {
                            OrderID = 7,
                            Freight = 70m,
                            OrderDate = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample7",
                            ShipName = "ShipNameExample7"
                        },
                        new
                        {
                            OrderID = 8,
                            Freight = 80m,
                            OrderDate = new DateTime(2022, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample8",
                            ShipName = "ShipNameExample8"
                        },
                        new
                        {
                            OrderID = 9,
                            Freight = 90m,
                            OrderDate = new DateTime(2022, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample9",
                            ShipName = "ShipNameExample9"
                        },
                        new
                        {
                            OrderID = 10,
                            Freight = 100m,
                            OrderDate = new DateTime(2022, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample10",
                            ShipName = "ShipNameExample10"
                        },
                        new
                        {
                            OrderID = 11,
                            Freight = 110m,
                            OrderDate = new DateTime(2022, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample11",
                            ShipName = "ShipNameExample11"
                        },
                        new
                        {
                            OrderID = 12,
                            Freight = 120m,
                            OrderDate = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample12",
                            ShipName = "ShipNameExample12"
                        },
                        new
                        {
                            OrderID = 13,
                            Freight = 130m,
                            OrderDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample13",
                            ShipName = "ShipNameExample13"
                        },
                        new
                        {
                            OrderID = 14,
                            Freight = 140m,
                            OrderDate = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample14",
                            ShipName = "ShipNameExample14"
                        },
                        new
                        {
                            OrderID = 15,
                            Freight = 150m,
                            OrderDate = new DateTime(2022, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample15",
                            ShipName = "ShipNameExample15"
                        },
                        new
                        {
                            OrderID = 16,
                            Freight = 160m,
                            OrderDate = new DateTime(2022, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample16",
                            ShipName = "ShipNameExample16"
                        },
                        new
                        {
                            OrderID = 17,
                            Freight = 170m,
                            OrderDate = new DateTime(2022, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample17",
                            ShipName = "ShipNameExample17"
                        },
                        new
                        {
                            OrderID = 18,
                            Freight = 180m,
                            OrderDate = new DateTime(2022, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample18",
                            ShipName = "ShipNameExample18"
                        },
                        new
                        {
                            OrderID = 19,
                            Freight = 190m,
                            OrderDate = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample19",
                            ShipName = "ShipNameExample19"
                        },
                        new
                        {
                            OrderID = 20,
                            Freight = 200m,
                            OrderDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample20",
                            ShipName = "ShipNameExample20"
                        },
                        new
                        {
                            OrderID = 21,
                            Freight = 210m,
                            OrderDate = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample21",
                            ShipName = "ShipNameExample21"
                        },
                        new
                        {
                            OrderID = 22,
                            Freight = 220m,
                            OrderDate = new DateTime(2022, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample22",
                            ShipName = "ShipNameExample22"
                        },
                        new
                        {
                            OrderID = 23,
                            Freight = 230m,
                            OrderDate = new DateTime(2022, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample23",
                            ShipName = "ShipNameExample23"
                        },
                        new
                        {
                            OrderID = 24,
                            Freight = 240m,
                            OrderDate = new DateTime(2022, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample24",
                            ShipName = "ShipNameExample24"
                        },
                        new
                        {
                            OrderID = 25,
                            Freight = 250m,
                            OrderDate = new DateTime(2022, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample25",
                            ShipName = "ShipNameExample25"
                        },
                        new
                        {
                            OrderID = 26,
                            Freight = 260m,
                            OrderDate = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample26",
                            ShipName = "ShipNameExample26"
                        },
                        new
                        {
                            OrderID = 27,
                            Freight = 270m,
                            OrderDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample27",
                            ShipName = "ShipNameExample27"
                        },
                        new
                        {
                            OrderID = 28,
                            Freight = 280m,
                            OrderDate = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample28",
                            ShipName = "ShipNameExample28"
                        },
                        new
                        {
                            OrderID = 29,
                            Freight = 290m,
                            OrderDate = new DateTime(2022, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample29",
                            ShipName = "ShipNameExample29"
                        },
                        new
                        {
                            OrderID = 30,
                            Freight = 300m,
                            OrderDate = new DateTime(2022, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipCity = "ShipCityExample30",
                            ShipName = "ShipNameExample30"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
